# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15.0.1
      - name: Add sebipom to settings.xml
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "fontysvenlo.org", "url": "https://www.fontysvenlo.org/repository" }]'
          plugin_groups: '[ "org.sonarsource.scanner.maven" ]'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: cd implementation && mvn -DCI=TRUE test --batch-mode --fail-at-end

      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
